apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zeppelin
  labels:
    app: zeppelin
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 22321 
      targetPort: 22321
      protocol: TCP
      name: driver-port
  selector:
    app: zeppelin
