apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"Prometheus","metadata":{"annotations":{},"labels":{"app":"kube-prometheus-stack-prometheus","app.kubernetes.io/instance":"kube-prometheus-stack","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/part-of":"kube-prometheus-stack","app.kubernetes.io/version":"56.6.2","chart":"kube-prometheus-stack-56.6.2","heritage":"Helm","release":"kube-prometheus-stack"},"name":"kube-prometheus-stack-prometheus","namespace":"default"},"spec":{"alerting":{"alertmanagers":[{"apiVersion":"v2","name":"kube-prometheus-stack-alertmanager","namespace":"default","pathPrefix":"/","port":"http-web"}]},"enableAdminAPI":false,"externalUrl":"http://kube-prometheus-stack-prometheus.default:9090","hostNetwork":false,"image":"quay.io/prometheus/prometheus:v2.49.1","listenLocal":false,"logFormat":"logfmt","logLevel":"info","paused":false,"podMonitorNamespaceSelector":{},"podMonitorSelector":{},"portName":"http-web","probeNamespaceSelector":{},"probeSelector":{"matchLabels":{"release":"kube-prometheus-stack"}},"replicas":1,"retention":"168h","routePrefix":"/","ruleNamespaceSelector":{},"ruleSelector":{"matchLabels":{"release":"kube-prometheus-stack"}},"scrapeConfigNamespaceSelector":{},"scrapeConfigSelector":{"matchLabels":{"release":"kube-prometheus-stack"}},"securityContext":{"fsGroup":2000,"runAsGroup":2000,"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}},"serviceAccountName":"kube-prometheus-stack-prometheus","serviceMonitorNamespaceSelector":{},"serviceMonitorSelector":{},"shards":1,"storage":{"volumeClaimTemplate":{"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"local-path"}}},"tsdb":{"outOfOrderTimeWindow":"0s"},"version":"v2.49.1","walCompression":true}}
    creationTimestamp: "2026-01-02T06:23:51Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-prometheus
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 56.6.2
      chart: kube-prometheus-stack-56.6.2
      heritage: Helm
      release: kube-prometheus-stack
    name: kube-prometheus-stack-prometheus
    namespace: default
    resourceVersion: "4582"
    uid: 8480004a-bbdc-447b-999f-ca06890bd79e
  spec:
    alerting:
      alertmanagers:
      - apiVersion: v2
        name: kube-prometheus-stack-alertmanager
        namespace: default
        pathPrefix: /
        port: http-web
    enableAdminAPI: false
    evaluationInterval: 30s
    externalUrl: http://kube-prometheus-stack-prometheus.default:9090
    hostNetwork: false
    image: quay.io/prometheus/prometheus:v2.49.1
    listenLocal: false
    logFormat: logfmt
    logLevel: info
    paused: false
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    portName: http-web
    probeNamespaceSelector: {}
    probeSelector:
      matchLabels:
        release: kube-prometheus-stack
    replicas: 1
    retention: 168h
    routePrefix: /
    ruleNamespaceSelector: {}
    ruleSelector:
      matchLabels:
        release: kube-prometheus-stack
    scrapeConfigNamespaceSelector: {}
    scrapeConfigSelector:
      matchLabels:
        release: kube-prometheus-stack
    scrapeInterval: 30s
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    serviceAccountName: kube-prometheus-stack-prometheus
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    shards: 1
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: local-path
    tsdb:
      outOfOrderTimeWindow: 0s
    version: v2.49.1
    walCompression: true
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-02T07:35:06Z"
      message: ""
      observedGeneration: 1
      reason: ""
      status: "True"
      type: Available
    - lastTransitionTime: "2026-01-02T07:35:06Z"
      message: ""
      observedGeneration: 1
      reason: ""
      status: "True"
      type: Reconciled
    paused: false
    replicas: 1
    selector: app.kubernetes.io/instance=kube-prometheus-stack-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=kube-prometheus-stack-prometheus,prometheus=kube-prometheus-stack-prometheus
    shardStatuses:
    - availableReplicas: 1
      replicas: 1
      shardID: "0"
      unavailableReplicas: 0
      updatedReplicas: 1
    shards: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
