apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml

configMapGenerator:
  - name: global-config
    envs:
      - global-config.env
  - name: spark-log4j
    files:
      - log4j.properties
