apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-spark-defaults
  labels:
    app: spark-platform
data:
  spark-defaults.conf: |
{{ .Values.global.spark.sparkDefaults | indent 4 }}
  log4j.properties: |
    # Set everything to be logged to the console
    rootLogger.level = INFO
    rootLogger.appenderRef.stdout.ref = STDOUT
