apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hive-metastore
  labels:
    app: hive-metastore
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9083
      protocol: TCP
      name: metastore
  selector:
    app: hive-metastore
