apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Generated Helm Chart
  - charts/gen/unity-catalog.yaml
  # Unity Catalog server configuration with S3/MinIO settings
  - unity-catalog-server-config.yaml

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
  - ingress-patch.yaml
