apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hive-server
  labels:
    app: hive-server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.thriftPort }}
      targetPort: 10000
      protocol: TCP
      name: thrift
    - port: {{ .Values.service.webUiPort }}
      targetPort: 10002
      protocol: TCP
      name: webui
  selector:
    app: hive-server
